config/routes.rb
Rails.application.routes.draw do

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "about" => 'public/homes#about'

  scope module: :public do
   delete "cart_products/destroy_all" => "cart_products#destroy_all"
   get "orders/thanks" => "orders#thanks"
   post "orders/confirm" => "orders#confirm"
   get "members/my_page" => "members#show"
   get "members/unsubscribe" =>"members#unsubscribe"
   get "members/my_page/edit" => "members#edit"
   patch "members/withdraw" => "members#withdraw"
   patch "members/my_page" => "members#update"
   resources :products, only:[:index, :show]
   resources :cart_products, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :create, :index, :show]
   resources :delivery_addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
   root to: 'homes#top'
   resources :products, only:[:index, :show, :new, :edit, :create, :update]
   resources :genres, only:[:index, :edit, :create, :update]
   resources :members, only:[:index, :show, :edit, :update]
   resources :orders, only:[:show, :update] do
     resources :order_products, only:[:update]
   end
  end
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy

 validates :last_name, presence: true
 validates :first_name, presence: true
 validates :last_name_kana, presence: true
 validates :first_name_kana, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :phone_number, presence: true

end

app/controllers/admin/members_controller.rb
class Admin::MembersController < ApplicationController
   before_action :authenticate_admin!
   layout 'admin/application'

  def index
    @members = Member.page(params[:page])
  end

  def show
    @member = Member.find(params[:id])
  end

  def edit
    @member = Member.find(params[:id])
  end

  def update
    @member = Member.find(params[:id])
    if @member.update(member_params)
      flash[:notice] = "会員情報を更新しました"
      redirect_to admin_member_path(@member)
    else
      flash[:alert] = "会員情報の更新に失敗しました"
      render :edit
    end
  end

  private
  def member_params
     params.require(:member).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :is_deleted, :postal_code, :address, :phone_number)
  end
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/views/admin/members/edit.html.erb
<div class = "container">
  <div class = "row my-5">
    <div class = "col-5">
      <h2 class = "w-auto h-75 p-2 text-center"><%= @member.last_name %><%= @member.first_name %>さんの会員情報編集</h4>
    </div>
  </div>

<%= render "layouts/error", obj: @member %>
<%= form_with model:@member, url: admin_member_path(@member.id), method: :patch do |f| %>

  <div class = "row ml-0 mb-4">
    <table class = "col-3">
      <tr>
       <th>会員ID</th>
       <td><%= @member.id %></td>
      </tr>
    </table>
  </div>

<%= render "public/members/member-info", f: f %>

  <div class = "row ml-0">
    <table class = "col-4">
      <tr>
        <th>会員ステータス</th>
        <td>
          <%= f.radio_button :is_deleted, false %>
          <%= f.label :is_deleted, "有効", value: false %>
          <%= f.radio_button :is_deleted, true %>
          <%= f.label :is_deleted, "退会", value: true %>
        </td>
      </tr>
    </table>
  </div>

  <div class = "row my-5  ml-0">
    <div class = "col-4 offset-1 text-center">
      <%= button_tag(type: "submit", class: "btn bgleft btn-sm shadow-sm ml-2") do %>
        <span>
          <i class="fas fa-save"></i> 変更を保存
        </span>
      <% end %>
    </div>
  </div>
<% end %>

</div>

app/views/admin/members/index.html.erb
<div class="container">
  <div class="p-3 mb-2">
    <h2 class="py-3 font-weight-bold">会員一覧</h2>

    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="font-weight-bold table-secondary">会員ID</th>
          <th class="font-weight-bold table-secondary">氏名</th>
          <th class="font-weight-bold table-secondary">メールアドレス</th>
          <th class="font-weight-bold table-secondary">ステータス</th>
        </tr>
      </thead>

      <tbody class="p-3 mb-2 bg-white">
        <% @members.each do |member| %>
        <tr>
          <td>
            <%= member.id %>
          </td>
          <td style="text-decoration:underline;">
            <%= link_to admin_member_path(member), class:"text-dark" do %>
              <%= member.last_name %><%= member.first_name %>
            <% end %>
          </td>
          <td>
            <%= member.email %>
          </td>
          <% if member.is_deleted==true %>
         <td class="text-danger font-weight-bold">退会</td>
          <% else %>
         <td class="text-success font-weight-bold">有効</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row justify-content-center">
      <div class="col-md-3">
        <%= paginate @members %>
      </div>
    </div>
  </div>
</div>

app/views/admin/members/show.html.erb
<div class="container">
  <div class="w-50 d-flex align-items-center justify-content-center my-5 ml-5">
    <h2 class="font-weight-bold"><%= @member.last_name %><%= @member.first_name %>さんの会員詳細</span>
  </div>
  <div class="row">
    <div class="col-sm-11 offset-md-1">
      <table class="table table-borderless">
        <tr>
         <th scope="col" style="width: 20%">会員ID</th>
         <td scope="col" style="width: 80%"><%= @member.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @member.last_name %> <%= @member.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @member.last_name_kana %> <%= @member.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @member.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @member.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @member.phone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @member.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @member.is_deleted == false %>
              <strong class="text-success">有効</strong>
              <% elsif @member.is_deleted == true %>
              <strong class="text-danger">退会</strong>
            <% end %>
          </td>
        </tr>
        <tr>
          <th></th>
          <td>
            <%= link_to edit_admin_member_path(@member), class: "btn bgleft mr-5" do %>
              <span>
                <i class="fas fa-cog"></i> 編集する
              </span>
            <% end %>
            <%= link_to admin_root_path, class: "btn bgleft" do %>
              <span>
                <i class="far fa-eye"></i> 注文履歴一覧
              </span>
            <% end %>
          </td>
        </tr>
      </table>
    </div>
  </div>
</div>