config/routes.rb
Rails.application.routes.draw do

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "about" => 'public/homes#about'

  scope module: :public do
   delete "cart_products/destroy_all" => "cart_products#destroy_all"
   get "orders/thanks" => "orders#thanks"
   post "orders/confirm" => "orders#confirm"
   get "members/my_page" => "members#show"
   get "members/unsubscribe" =>"members#unsubscribe"
   get "members/my_page/edit" => "members#edit"
   patch "members/withdraw" => "members#withdraw"
   patch "members/my_page" => "members#update"
   resources :products, only:[:index, :show]
   resources :cart_products, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :create, :index, :show]
   resources :delivery_addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
   root to: 'homes#top'
   resources :products, only:[:index, :show, :new, :edit, :create, :update]
   resources :genres, only:[:index, :edit, :create, :update]
   resources :members, only:[:index, :show, :edit, :update]
   resources :orders, only:[:show, :update] do
     resources :order_products, only:[:update]
   end
  end
end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
   before_action :authenticate_admin!
   layout 'admin/application'

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを新規登録しました"
     redirect_to admin_genres_path
    else
      @genres = Genre.all
     render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル名を保存しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/views/admin/genres/edit.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-3 offset-1 my-5">
      <h4 class = "w-auto h-75 p-2 text-center">ジャンル編集</h4>
    </div>
  </div>

  <%= form_with model: @genre, url:admin_genre_path(@genre) do |f| %>
  <div class = "row">
  <%= render 'layouts/error', obj: @genre %>
    <div class = "col-2">
      <%= f.label :name, "ジャンル名" %>
    </div>
    <div class = "col-4">
      <%= f.text_field :name, class: "form-control" %>
    </div>
    <div class = "col-3">
      <%= button_tag(type: "submit", class: "btn bgleft btn-sm shadow-sm ml-2") do %>
        <span>
          <i class="fas fa-save"></i> 保存する
        </span>
      <% end %>
  </div>
  <% end %>


</div>

app/views/admin/genres/index.html.erb
<div class = "container">
  <div class = "row">
    <div class = "col-3 offset-1 mt-5">
      <h4 class = "w-auto h-75 p-2 text-center">ジャンル一覧・追加</h4>
    </div>
  </div>



<%= form_with model:@genre, url:admin_genres_path do |f| %>
<%= render 'layouts/error', obj: @genre %>
  <div class = "row mt-5">
    <div class = "col-2">
      <%= f.label :name, "ジャンル名" %>
    </div>
    <div class = "col-4">
      <%= f.text_field :name, placeholder: "ジャンル名", class: "form-control" %>
    </div>
    <div class = "col-2">
      <%= button_tag(type: "submit", class: "btn bgleft btn-sm shadow-sm ml-2") do %>
        <span>
         追加
        </span>
      <% end %>
    </div>
  </div>
<% end %>

  <div class = "row my-5">
    <table class = "col-4">
      <thead class = "w-75 p-2 text-center border-top border-bottom" style="background-color: #eee;">
        <tr>
          <th>ジャンル</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @genres.each do |genre| %>
          <tr>
            <td class = "text-left"><%= genre.name %></td>
            <td class = "text-right">
              <%= link_to edit_admin_genre_path(genre.id), class: "btn bgleft btn-sm px-4 mb-2" do %>
                <span><i class="fas fa-cog"></i> 編集</span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

</div>