config/routes.rb
Rails.application.routes.draw do

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "about" => 'public/homes#about'

  scope module: :public do
   delete "cart_products/destroy_all" => "cart_products#destroy_all"
   get "orders/thanks" => "orders#thanks"
   post "orders/confirm" => "orders#confirm"
   get "members/my_page" => "members#show"
   get "members/unsubscribe" =>"members#unsubscribe"
   get "members/my_page/edit" => "members#edit"
   patch "members/withdraw" => "members#withdraw"
   patch "members/my_page" => "members#update"
   resources :products, only:[:index, :show]
   resources :cart_products, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :create, :index, :show]
   resources :delivery_addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
   root to: 'homes#top'
   resources :products, only:[:index, :show, :new, :edit, :create, :update]
   resources :genres, only:[:index, :edit, :create, :update]
   resources :members, only:[:index, :show, :edit, :update]
   resources :orders, only:[:show, :update] do
     resources :order_products, only:[:update]
   end
  end
end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  has_many :order_products, dependent: :destroy
  has_many :cart_products, dependent: :destroy

  validates :product_image,presence:true
  validates :name,presence:true
  validates :text,presence:true,length:{maximum:200}
  validates :genre_id,presence:true
  validates :price,presence:true
  validates :sales_status, inclusion: {in: [true, false]}



  has_one_attached :product_image

  def get_product_image(width, height)
    product_image.variant(resize_to_limit: [width, height]).processed
  end

  def sum_of_order_price
    (price * 1.1).floor
  end

end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin/application'

  def show
    @product = Product.find(params[:id])

  end

  def index
     @products = Product.page(params[:page])
  end

  def new
    @product = Product.new
    @genres = Genre.all
  end

  def create
    @product = Product.new(product_params)
    if @product.save
      flash[:notice] = "商品を登録しました"
      redirect_to admin_product_path(@product)
    else
      @genres = Genre.all
      render :new
    end
  end

  def edit
    @product = Product.find(params[:id])
    @genres = Genre.all
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:notice] = "商品情報を更新しました"
      redirect_to admin_product_path(@product)
    else
      @genres = Genre.all
      render :edit
    end
  end

  private
  def product_params
    params.require(:product).permit(:name, :text, :genre_id, :price, :sales_status, :product_image)
  end

end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/views/admin/products/edit.html.erb
<div class="container">
  <div class="w-25 d-flex align-items-center justify-content-center my-5 ml-5">
    <h2 class="font-weight-bold">商品編集</span>
  </div>

  <div class="row">
    <div class="col-sm-10 offset-md-2">

    <%= form_with model: [:admin, @product], local:true do |f| %>
    <%= render 'layouts/error', obj: @product %>
    <div class="form-group row">
      <%= f.label :image, "商品画像", class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
      <%= f.file_field :product_image, accept: 'image/*', class: "form-control-plaintext" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :name, "商品名", class: "col-md-2 col-form-label" %>
      <div class="col-md-5">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :text, "商品説明", class: "col-md-2 col-form-label" %>
      <div class="col-md-5">
        <%= f.text_area :text, rows: 6, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :genre, "ジャンル", class: "col-md-2 col-form-label" %>
      <div class="col-md-5">
        <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"}, {class: "form-control"}) %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :price, "税抜価格", class: "col-md-2 col-form-label" %>
      <div class="col-auto d-flex flex-row">
        <%= f.text_field :price, class: "form-control" %><span class="my-auto ml-2">円</span>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :sales_status, "販売ステータス", class: "col-md-2 col-form-label" %>
      <div class="col-md-10 my-2">
        <%= f.radio_button :sales_status, true %>
        <%= f.label :sales_status, "販売中", value: true, class: "mr-3" %>
        <%= f.radio_button :sales_status, false %>
        <%= f.label :sales_status, "販売停止中", value: false %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-5 offset-2">
        <%= button_tag(type: "submit", class: "btn bgleft btn-sm shadow-sm ml-2") do %>
          <span>
           <i class="fas fa-save"></i> 変更を保存
          </span>
        <% end %>
      </div>
    </div>

    <% end %>

    </div>
  </div>
</div>

app/views/admin/products/index.html.erb
<div class="container">
  <div class="p-3 mb-2">
    <h2 class="py-3">商品一覧</h2>
    <div class="offset-11 mb-3">
      <div class="iconbox">
        <%= link_to new_admin_product_path do %>
          <i class="fas fa-plus"></i>
        <% end %>
      </div>
    </div>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th class="font-weight-bold table-secondary">商品ID</th>
          <th class="font-weight-bold table-secondary">商品名</th>
          <th class="font-weight-bold table-secondary">税抜価格</th>
          <th class="font-weight-bold table-secondary">ジャンル</th>
          <th class="font-weight-bold table-secondary">ステータス</th>
        </tr>
      </thead>

      <tbody class="p-3 mb-2 bg-white">
        <% @products.each do |product| %>
        <tr>
          <td><%= product.id %></td>
          <td style="text-decoration:underline;">
            <%= link_to admin_product_path(product), class:"text-dark" do %>
              <%= product.name %>
            <% end %>
          </td>
          <td><%= product.price %>円</td>
          <td><%= product.genre.name%></td>
          <% if product.sales_status==true %>
           <td class="text-success font-weight-bold">販売中</td>
          <% else %>
           <td class="text-danger font-weight-bold">販売停止中</td>
          <% end %>
        </tr>
        <% end %>
      </tbody>
    </table>

    <div class="row justify-content-center">
      <div class="col-3">
        <%= paginate @products %>
      </div>
    </div>
  </div>
</div>

app/views/admin/products/new.html.erb
<div class="container">
  <div class="w-25 d-flex align-items-center justify-content-center my-5 ml-5">
    <h2 class="font-weight-bold">商品新規登録</span>
  </div>

  <div class="row">
    <div class="col-sm-10 offset-md-2">

    <%= form_with model: [:admin, @product], local:true do |f| %>
    <%= render 'layouts/error', obj: @product %>
    <div class="form-group row">
      <%= f.label :image, "商品画像", class: "col-md-2 col-form-label" %>
      <div class="col-md-10">
      <%= f.file_field :product_image, accept: 'image/*', class: "form-control-plaintext" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :name, "商品名", class: "col-md-2 col-form-label" %>
      <div class="col-md-5">
        <%= f.text_field :name, placeholder: "商品名", class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :text, "商品説明", class: "col-md-2 col-form-label" %>
      <div class="col-md-5">
        <%= f.text_area :text, placeholder: "ここに説明文を記述します", rows: 6, class: "form-control" %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :genre, "ジャンル", class: "col-md-2 col-form-label" %>
      <div class="col-md-5">
        <%= f.collection_select(:genre_id, @genres, :id, :name, {prompt: "選択してください"}, {class: "form-control"}) %>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :price, "税抜価格", class: "col-md-2 col-form-label" %>
      <div class="col-auto d-flex flex-row">
        <%= f.text_field :price, placeholder: "1000", class: "form-control" %><span class="my-auto ml-2">円</span>
      </div>
    </div>
    <div class="form-group row">
      <%= f.label :sales_status, "販売ステータス", class: "col-md-2 col-form-label" %>
      <div class="col-md-10 my-2">
        <%= f.radio_button :sales_status, true, checked: true  %>
        <%= f.label :sales_status, "販売中", value: true, class: "mr-3" %>
        <%= f.radio_button :sales_status, false %>
        <%= f.label :sales_status, "販売停止中", value: false %>
      </div>
    </div>
    <div class="form-group row">
      <div class="col-5 offset-2">
        <%= button_tag(type: "submit", class: "btn bgleft btn-sm shadow-sm ml-2") do %>
          <span>
            新規登録
          </span>
        <% end %>
      </div>
    </div>

    <% end %>

    </div>
  </div>
</div>

app/views/admin/products/show.html.erb
<div class='container'>
  <div class='row'>
    <div class="offset-md-1 col-md-3">
      <h2 class="py-4">商品詳細</h2>
    </div>
  </div>

  <div class="row mt-3">
    <div class="col-lg-6">
      <div class="product-image-show">
        <%= image_tag @product.get_product_image(475,315) %>
      </div>
    </div>

    <div class="col-lg-6">
      <div class="row">
        <div class="col-lg-4 text-right">
          <label>商品名:</label>
        </div>
        <div class="col-lg-8">
          <p><%= @product.name %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 text-right">
          <label>商品説明:</label>
        </div>
        <div class="col-lg-8">
          <p><%= @product.text %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 text-right">
          <label>ジャンル:</label>
        </div>
        <div class="col-lg-8">
          <p><%= @product.genre.name %></p>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 text-right">
          <label>
             税込価格:<br/>
             (税抜価格):
          </label>
        </div>
        <div class="col-lg-8">
          <p>
            <%= @product.sum_of_order_price %><br>
            (<%= @product.price %>)円
          </p>
        </div>
      </div>

      <div class="row">
        <div class="col-lg-4 text-right">
          <label>販売ステータス:</label>
        </div>
        <% if @product.sales_status %>
          <div class="col-lg-8">
            <p class="text-success">販売中</p>
          </div>
        <% else %>
          <div class="col-lg-8">
            <p class="text-danger">販売停止中</p>
          </div>
        <% end %>
      </div>

　　　<div class="row justify-content-center m-0">
　　　  <div class="col-lg-8">
　　　    <%= link_to edit_admin_product_path(@product), class: "btn btn-block bgleft " do %>
            <span><i class="fas fa-cog"></i> 編集する</span>
          <% end %>
　　　  </div>
　　　</div>
    </div>
  </div>
</div>