config/routes.rb
Rails.application.routes.draw do

  devise_for :members, skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords], controllers: {
    sessions: "admin/sessions"
  }

  root to: "public/homes#top"
  get "about" => 'public/homes#about'

  scope module: :public do
   delete "cart_products/destroy_all" => "cart_products#destroy_all"
   get "orders/thanks" => "orders#thanks"
   post "orders/confirm" => "orders#confirm"
   get "members/my_page" => "members#show"
   get "members/unsubscribe" =>"members#unsubscribe"
   get "members/my_page/edit" => "members#edit"
   patch "members/withdraw" => "members#withdraw"
   patch "members/my_page" => "members#update"
   resources :products, only:[:index, :show]
   resources :cart_products, only:[:index, :create, :update, :destroy]
   resources :orders, only:[:new, :create, :index, :show]
   resources :delivery_addresses, only:[:index, :create, :edit, :update, :destroy]
  end

  namespace :admin do
   root to: 'homes#top'
   resources :products, only:[:index, :show, :new, :edit, :create, :update]
   resources :genres, only:[:index, :edit, :create, :update]
   resources :members, only:[:index, :show, :edit, :update]
   resources :orders, only:[:show, :update] do
     resources :order_products, only:[:update]
   end
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_product.rb
class CartProduct < ApplicationRecord
  belongs_to :product
  belongs_to :member

  validates :quantity,presence:true


  def subtotal
    product.sum_of_order_price * quantity
  end

end

app/models/delivery_address.rb
class DeliveryAddress < ApplicationRecord
  belongs_to :member


  validates :address, :shipping_name, presence: true

  def address_display
  '〒' + postal_code + ' ' + address + ' ' + shipping_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :products, dependent: :destroy

  validates :name, presence: true
end

app/models/member.rb
class Member < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :orders, dependent: :destroy
  has_many :delivery_addresses, dependent: :destroy
  has_many :cart_products, dependent: :destroy

 validates :last_name, presence: true
 validates :first_name, presence: true
 validates :last_name_kana, presence: true
 validates :first_name_kana, presence: true
 validates :postal_code, presence: true
 validates :address, presence: true
 validates :phone_number, presence: true

end

app/models/order.rb
class Order < ApplicationRecord

  belongs_to :member
  has_many :order_products, dependent: :destroy

  enum payment_method: { credit_card: 0, transfer: 1 }
  enum order_status: { wait_payment: 0, confirm_payment: 1, making: 2, preparing_ship: 3, sent: 4 }

  validates :member_id, presence: true
  validates :shipping, presence: true
  validates :shipping_postal_code, presence: true
  validates :shipping_address, presence: true
  validates :shipping_name, presence: true
  validates :payment_method, presence: true
  validates :order_status, presence: true
  validates :billing_amount, presence: true
  
  def sum_of_order_price
    (billing_amount - shipping).round
  end

  def address_display_order
    '〒' + shipping_postal_code + ' ' + shipping_address
  end

end

app/models/order_product.rb
class OrderProduct < ApplicationRecord

  belongs_to :order
  belongs_to :product

  enum product_status: { impossible_manufacture: 0, waiting_manufacture: 1, manufacturing: 2, finish: 3 }

  validates :order_id, :product_id, :quantity, :price, presence:true

    def quantity_price
      (product.sum_of_order_price * quantity).round
    end

end

app/models/product.rb
class Product < ApplicationRecord

  belongs_to :genre
  has_many :order_products, dependent: :destroy
  has_many :cart_products, dependent: :destroy

  validates :product_image,presence:true
  validates :name,presence:true
  validates :text,presence:true,length:{maximum:200}
  validates :genre_id,presence:true
  validates :price,presence:true
  validates :sales_status, inclusion: {in: [true, false]}



  has_one_attached :product_image

  def get_product_image(width, height)
    product_image.variant(resize_to_limit: [width, height]).processed
  end

  def sum_of_order_price
    (price * 1.1).floor
  end

end

app/models/public.rb
class Public < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
   before_action :authenticate_admin!
   layout 'admin/application'

  def index
    @genres = Genre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      flash[:notice] = "ジャンルを新規登録しました"
     redirect_to admin_genres_path
    else
      @genres = Genre.all
     render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      flash[:notice] = "ジャンル名を保存しました"
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private

  def genre_params
    params.require(:genre).permit(:name)
  end
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
   before_action :authenticate_admin!
   layout 'admin/application'

  def top
    @orders = Order.page(params[:page]).order(id: :DESC)
    @total_quantity = 0
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  layout 'admin/application'

  def show
    @order = Order.find(params[:id])
    @order_products = @order.order_products
    @order_product = OrderProduct.find(params[:id])
  end

  def update
     @order = Order.find(params[:id])
     @order_products = @order.order_products
     @order.update(order_params)
     flash[:notice] = "更新しました"
    if @order.order_status == "confirm_payment"
      @order_products.update_all(product_status: "waiting_manufacture")
      redirect_to admin_order_path(@order)
    else
      redirect_to admin_order_path(@order)
    end
  end

  private

  def order_params
  params.require(:order).permit(:order_status)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  

end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/members_helper.rb
module Admin::MembersHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/_error.html.erb
<% if obj.errors.any? %>
  <div id="error_explanation">
    <h3><%= pluralize(obj.errors.count, "error") %> prohibited this obj from being saved:</h3>
    <ul>
      <% obj.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer>
  <div class="card-footer text-muted d-flex justify-content-center">
    <i class="fas fa-frog mr-2"></i>
    <i class="fas fa-frog mr-2"></i>
    <i class="fas fa-frog"></i>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-dark shadow-sm">
    <div class="container">
      <a class="navbar-brand" href="/"><i class="fas fa-birthday-cake"></i> Nagano Cake</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNavDropdown">
        <ul class="navbar-nav ml-auto">
        <% if admin_signed_in? %>
          <li class="nav-item">
            <%= link_to "商品一覧", admin_products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "会員一覧", admin_members_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "注文履歴一覧", admin_root_path, class: "nav-link" %>
          </li>
           <li class="nav-item">
            <%= link_to "ジャンル一覧", admin_genres_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログアウト", destroy_admin_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "About", about_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "商品一覧", products_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "新規登録", new_member_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "ログイン", new_admin_session_path, class: "nav-link" %>
          </li>
        <% end %>
          <div class="ml-5">
            <form class="form-inline ml-auto">
              <input type="text" class="form-control" placeholder="Search">
              <button type="submit" class="btn bgleft btn-sm"><span>検索</span></button>
            </form>
          </div>

        </ul>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <%= render 'layouts/admin/header' %>
   <main>
     <% if flash[:notice] %>
      <p id="notice" class="alert alert-success"><%= notice %></p>
     <% end %>
     <% if flash[:alert] %>
      <p id="alert" class="alert alert-danger"><%= alert %></p>
     <% end %>
     <%= yield %>
   </main><%= render "layouts/footer" %>
  </body>
</html>

app/views/layouts/admin/application.jtml.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/admin/header' %>
   <main>
     <%= yield %>
   </main>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
   <main>
     <%= yield %>
   </main>
  </body>
</html>